---
title: "Dashboard Using Plotly (Data:Instacart)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```



Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}

data(instacart)
instacart %>% 
  filter(order_dow==0|order_dow==6) %>% 
  count(department) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter(order_dow==0|order_dow==6) %>% 
  count(order_hour_of_day) %>% 
  plot_ly(x= ~order_hour_of_day, y = ~n, type = 'scatter', mode = 'lines',
          colors = "Set2")
```

### Chart C

```{r}
instacart %>% 
  filter(order_dow==0|order_dow==6) %>% 
  plot_ly(y = ~days_since_prior_order, type = 'box',color = ~department,
          colors = "Set2")
```